name: Codecov

on: [push]

jobs:

  build:
    name: Coverage
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Coverage
      run: |
        set -e
        echo "" > coverage.txt
        for d in $(go list ./... | grep -v vendor); do
            go test -race -coverprofile=profile.out -covermode=atomic "$d"
            if [ -f profile.out ]; then
                cat profile.out >> coverage.txt
                rm profile.out
            fi
        done

    - name: Upload To Codecov
      run: bash <(curl -s https://codecov.io/bash)
