name: Go

on:
  push:
    branches: [ master, sdttttt ]
  pull_request:
    branches: [ master, sdttttt ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Test
      run: go test -v -cover ./...

    - name: Build
      run: |
        cd cmd/
        go build -v ./...
