name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Run Revive Action by building from repository
      uses: morphy2k/revive-action@v1
      with:
        name: "Revive"
      env:
        # GitHub token for annotations (optional)
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

